### ISSUE TITLE
Suggestions/questions

### ISSUE THREAD

**Issue by npuldon** [raiguard/Factorio-RateCalculator#1]
1) Any timeline/plan to incorporate some of the other rates MaxRateCalc has (like inserters)?

2) What about modded belts with different speeds (also available with MaxRateCalc)?

3) A calculator where you can use the number pad on your keyboard? ( MaxRateCalc's built-in calculator only allow button presses with a mouse)

Thanks for your help.  The mod works great and looks nice but it still seems to be missing some features I use often from the other similar mod I mentioned.

Cheers

**Comment by raiguard** [comment]
Thanks for the feedback!

1. Inserters were part of the original plan, but got axed for the final product. The reason for this is that calculations surrounding inserters are so ridiculously complex and convoluted that it's impossible to produce accurate rates for them. MRC had hardcoded rate values for all vanilla inserters, but that didn't fly with me.

2. This mod supports any belts that exist in your game, including modded belts. Same goes for train wagons.

3. I didn't add a calculator because it's extremely easy to just use Windows' built-in calculator. I didn't see a need to add one.

Thanks again!

**Comment by npuldon** [comment]
1) Bit disappointing but I understand.  I don't use this feature much in vanilla but very often in modded.

2) Glad to hear it!

3) I guess that works if you have two monitors or if you don't mind alt tabbing the game if you have one monitor.   I just have one.  It does take away from the immersion a bit though having to alt+tab out of games to use utilities.  I can understand why you didn't put it in though, especially if you use two monitors.

**Comment by raiguard** [comment]
I have found a way to do inserters, and will add them eventually. Not now though.

**Comment by heipl-paul** [comment]
I didn't know which mod to use, so I downloaded both your "Rate Calculator", and the older "Max rate calculator". Tried them both, preferred yours, uninstalled the other, and ever since then I can't get it to work. 

I just do a selection and nothing happens. If I do a very large selection it interrupts the game a bit, but still no UI pops up.
Any place I can find logs or some such?

**Comment by npuldon** [comment]
> I didn't know which mod to use, so I downloaded both your "Rate Calculator", and the older "Max rate calculator". Tried them both, preferred yours, uninstalled the other, and ever since then I can't get it to work.

I have used them both in the past in the same game.  I don't remember any issues with using either calculator.  Odd.

**Comment by raiguard** [comment]
@heipl-paul That is very strange. Could you upload your save file so I can take a look? After that, try removing and re-adding the mod to reset everything, and see if that helps.
