### ISSUE TITLE
Support for heat exchangers

### ISSUE THREAD

**Issue by fbatista** [raiguard/Factorio-RateCalculator#19]
#### Is your feature request related to a problem? Please describe.

When using the rate calculator on a nuclear reactor, it doesn't take heat exchangers into account - it doesn't calculate the steam output / water consumption

#### Describe the solution you'd like

I'd love for it to pick up on those entities and calculate those 2 values.

As a nice to have, we could introduce a heat measure, having reactors as producers of heat and exchangers as consumers (not sure of this rate exactly, but it could be nice to use the neighbour bonus to output the correct value)

#### Additional context

no context

**Comment by raiguard** [comment]
Boilers and heat exchangers are surprisingly complicated, but this is on my list. :)

**Comment by fbatista** [comment]
It's understandable if you'd go all the way through the actual heat processing etc, but just implementing the same thing that regular boilers do (with 103steam/s output instead of 60) and the same for turbines (60steam/s consumption instead of 30 like the engines) would already be a good thing to have in the meantime. I'd do it myself, but i have no idea how factorio modding works... i guess i'll need some free time to look for documentation etc.

**Comment by raiguard** [comment]
As per your discussion on Discord, doing boilers and heat exchangers is completely impossible at the moment without a mod API addition. Leaving this here so the context of that conversation isn't lost.

**Comment by raiguard** [comment]
So, good news! We were looking in the wrong place this entire time. Rate Calculator needs the ideal (maximum) consumption, not the _current_ consumption. I took a peak at the game's source code and found the math they used to calculate the max consumption for the tooltip, copied that, and it works perfectly!

![image](https://user-images.githubusercontent.com/3515394/100644533-a8c9ae80-32f8-11eb-9e76-dddf9580e05d.png)

I'm going to leave this issue open since I haven't yet implemented the energy source calculations.
