### ISSUE TITLE
Inserters as rate unit

### ISSUE THREAD

**Issue by mkaito** [raiguard/Factorio-RateCalculator#62]
#### Is your feature request related to a problem? Please describe.

It would be useful to see how many inserters of a given type a machine needs for input and output, given the currently researched inserter capacity bonus.

#### Describe the solution you'd like

Calculating true inserter throughput is non-trivial (but feel free to give it a try, support for modded inserters would be awesome), but is well documented with empirical data on the wiki. It might not fit the current UI layout, but I'd like to be able to select the inserter type, source and target, specifying either chest or a belt type for source and target.

#### Additional context

It takes a fair amount of trial and error to figure out the best type and amount of inserter you need for highly optimized factory configurations, especially as the speed bonus starts piling up. Getting a ballpark figure from a calculator would help a lot.

**Comment by raiguard** [comment]
This is on my plan, but it will be tricky.

**Comment by Identifier** [comment]
+1

Yes, that is a critical feature in order to determine which type of inserter to place in order to prevent bottlenecks.  Please see https://mods.factorio.com/mod/MaxRateCalculator.  Specifically this image: https://mods-data.factorio.com/assets/a1596eb183378afa6299a581a069dd955c640001.png

Your mod looks prettier than that one, and I'd like to switch to yours but it's missing that critical feature.  Actually, you could implement that feature even better than they do if you show all types of inserters at once.  Currently in https://mods.factorio.com/mod/MaxRateCalculator you have to use the dropdown to check each inserter one by one to see which ones are sufficient.

**Comment by raiguard** [comment]
The reason why it's tricky is because Max Rate Calculator naively hardcodes average rates for each kind of inserter. It does not account for pickup and drop off position or the source and destination types (container vs. belt). It's not very accurate most of the time.

What you'll have to do with Rate Calculator is select the inserter to measure with a selection tool, after you've already placed it. That will be the only way to get somewhat accurate measurements.

**Comment by raiguard** [comment]
![image](https://user-images.githubusercontent.com/3515394/117079112-6289d880-acf8-11eb-9601-201d208e9657.png)

Look what I just did!
