### ISSUE TITLE
Buildings are not recognized

### ISSUE THREAD

**Issue by kuxynator** [raiguard/Factorio-RateCalculator#64]
https://prnt.sc/10lgzsf
Mod: Mini Machines, maybe also Micro Machines and buildings from other mods.
Because all entities have a common type as base it should be possible to detect also "unknown"  buildings.
Use type instead of name for searching. what I mean is not to look for name == "assembly-machine-3" but for type =="assembly-machine"

**Comment by raiguard** [comment]
I just installed mini machines and it works fine. Can you send me a save file to sync with?

**Comment by raiguard** [comment]
Do these machines happen to be in Space?

**Comment by Pscx1** [comment]
Had the same issue but figured out what could cause issue and that was because **angel smelting/refining and petrochem proc** was enabled, without those mods it works just fine even on around 100 mods
Attached save file 
[TEST.zip](https://github.com/raiguard/Factorio-RateCalculator/files/6489580/TEST.zip)

**Comment by Paos-glitch** [comment]
Electic Furnaces, Krastorio 2, Krastorio 2 compat, Mini and Micro machines enabled together to test, rate calc not recognizing neither of micro or mini machines.
